# Generated by Django 4.1 on 2023-04-16 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="body_data",
            field=models.TextField(db_column="body_xml", verbose_name="Body"),
        ),
        migrations.AlterField(
            model_name="task",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Publish date"
            ),
        ),
        migrations.AlterField(
            model_name="taskcollection",
            name="exam_mode",
            field=models.IntegerField(
                choices=[
                    (0, "No Exam"),
                    (1, "No Solutions, only Right/Wrong"),
                    (2, "No Results, just continue quiz"),
                ],
                default=0,
            ),
        ),
    ]
