# Generated by Django 4.1 on 2023-04-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_task_body_data_alter_task_pub_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizresult",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="taggedmodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tc_membership",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
